[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["jpeg"] }
bevy_rapier3d = "0.28.0"
bevy_third_person_camera = "0.2.0"
iyes_perf_ui = {git='https://github.com/IyesGames/iyes_perf_ui.git', rev ='d8f3cbb'}
